// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_excercise/test/src/RitchieBros/repository/search_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_excercise/src/RitchieBros/models/rb_item.dart' as _i4;
import 'package:flutter_excercise/src/RitchieBros/services/rb_api_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RbApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRbApiService extends _i1.Mock implements _i2.RbApiService {
  MockRbApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.RBItem>> fetchAssets({
    int? from = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAssets,
          [],
          {
            #from: from,
            #size: size,
          },
        ),
        returnValue: _i3.Future<List<_i4.RBItem>>.value(<_i4.RBItem>[]),
      ) as _i3.Future<List<_i4.RBItem>>);
}
