// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_excercise/test/src/RitchieBros/viewmodels/rb_items_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_excercise/src/RitchieBros/models/rb_item.dart' as _i5;
import 'package:flutter_excercise/src/RitchieBros/repository/search_repository.dart'
    as _i3;
import 'package:flutter_excercise/src/RitchieBros/services/rb_api_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRbApiService_0 extends _i1.SmartFake implements _i2.RbApiService {
  _FakeRbApiService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SearchtRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchtRepository extends _i1.Mock implements _i3.SearchtRepository {
  MockSearchtRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RbApiService get rbApiService => (super.noSuchMethod(
        Invocation.getter(#rbApiService),
        returnValue: _FakeRbApiService_0(
          this,
          Invocation.getter(#rbApiService),
        ),
      ) as _i2.RbApiService);

  @override
  _i4.Future<List<_i5.RBItem>> getSearchResult({
    int? from = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSearchResult,
          [],
          {
            #from: from,
            #size: size,
          },
        ),
        returnValue: _i4.Future<List<_i5.RBItem>>.value(<_i5.RBItem>[]),
      ) as _i4.Future<List<_i5.RBItem>>);
}
